### PR TITLE
Replace shelljs.exec with child_process.execSync

### PR DESCRIPTION
**Pull request by jackofdiamond5**

### CODE REVIEW

**Comment by ViktorSlavov** [comment]
Installs, builds and serves properly but throws an error when `npm run start` is cancelled from the console (`Ctrl` + `C`):
```bash
(node:13412) UnhandledPromiseRejectionWarning: Error: Command failed: npm start -- --port=4242
    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:653:13)
    at Function.exec (C:\Users\VSlavov\Desktop\cli-test\node_modules\igniteui-cli\lib\Util.js:321:32)
    at Object.<anonymous> (C:\Users\VSlavov\Desktop\cli-test\node_modules\igniteui-cli\lib\commands\start.js:82:37)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\VSlavov\Desktop\cli-test\node_modules\igniteui-cli\lib\commands\start.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:13412) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:13412) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by damyanpetev** [comment]
@ViktorSlavov @jackofdiamond5 
You might have a point there. I remember there was some sort of special error code for interrupt (`Ctrl+C`) that could be intercepted and ignored. There might be something similar already in.. the package manager code.

**Comment by damyanpetev** [comment]
@jackofdiamond5 You can wrap the execSync in a try catch, something like:
https://github.com/IgniteUI/igniteui-cli/blob/e0f2b7ea822f7a230b855107e6a1498d2df8222a/lib/packages/PackageManager.ts#L88-L97

**Comment by ViktorSlavov** [comment]
It's still throwing the same error, as mentioned above.
Steps to reproduce:
 - Build and pack the repo locally
 - Install the package in a new folder
 - Run `ig new`
 - Make the following choices during init:
   - **Empty Project**
   - **Default Theme**
 - Regardless if you choose to add component views, choose `Complete & Run`

The app runs as expected.
Go back to the console and terminate the process w/ `Ctrl + C`.
Observe the error.

**Pull request merged**
